import{Report,ReportedPerson,Evidence,AuditLog,NotificationItem,PoliceUser,District,Upazila,Thana,UnionItem,VillageItem,PublicStatistics,ReportStatus,UserRole}from'../types';
import{db,isFirebaseConfigured,auth}from'../lib/firebase';
import{collection,doc,getDoc,getDocs,setDoc,updateDoc,query,where,orderBy,limit}from'firebase/firestore';
import{getDistricts as geoDistricts,getDivisions as geoDivisions,getUpazilas as geoUpazilas,getAreas as geoAreas,getVillages as geoVillages}from'../data/bdGeoData';

import{Report,ReportedPerson,Evidence,AuditLog,NotificationItem,PoliceUser,District,Upazila,Thana,UnionItem,VillageItem,PublicStatistics,ReportStatus,UserRole}from'../types';
import{db,isFirebaseConfigured,auth}from'../lib/firebase';
import{collection,doc,getDoc,getDocs,setDoc,updateDoc,query,where,orderBy,limit}from'firebase/firestore';
import{getDistricts as geoDistricts,getDivisions as geoDivisions,getUpazilas as geoUpazilas,getAreas as geoAreas,getVillages as geoVillages}from'../data/bdGeoData';

class DataService{
 private ready(){if(!isFirebaseConfigured||!db)throw new Error('Firebase is not configured.');return db}
 async getDistricts():Promise<District[]>{const divs=geoDivisions() as readonly any[];return(geoDistricts() as readonly any[]).map(d=>{const v=divs.find(x=>x.id===d.divisionId);return{id:`dist_${d.id}`,nameEn:d.name,nameBn:d.nameBn,division:v?.name||''}})}
 async getUpazilas(d?:string):Promise<Upazila[]>{const districtId=d?Number(d.replace('dist_','')):undefined;return(geoUpazilas() as readonly any[]).filter(u=>u.type==='upazila'&&(districtId==null||u.districtId===districtId)).map(u=>({id:`upz_${u.id}`,districtId:`dist_${u.districtId}`,nameEn:u.name,nameBn:u.nameBn}))}
 async getThanas(_u?:string,d?:string):Promise<Thana[]>{const districtId=d?Number(d.replace('dist_','')):undefined;return(geoUpazilas() as readonly any[]).filter(x=>x.type==='thana'&&(districtId==null||x.districtId===districtId)).map(x=>({id:`thana_${x.id}`,upazilaId:undefined,districtId:`dist_${x.districtId}`,nameEn:x.name,nameBn:x.nameBn,code:String(x.id)}))}
 async getUnions(u?:string):Promise<UnionItem[]>{const upazilaId=u?Number(u.replace('upz_','')):undefined;return(geoAreas() as readonly any[]).filter(a=>a.type==='union'&&(upazilaId==null||a.upazilaId===upazilaId)).map(a=>({id:`union_${a.id}`,thanaId:'',nameEn:a.name,nameBn:a.nameBn}))}
 async getVillages(u?:string):Promise<VillageItem[]>{const unionId=u?Number(u.replace('union_','')):undefined;return(geoVillages() as readonly any[]).filter(v=>unionId==null||v.areaId===unionId).map(v=>({id:`village_${v.id}`,unionId:`union_${v.areaId}`,nameEn:v.name,nameBn:v.nameBn}))}

 async getReports(role:UserRole,uid:string,thana?:string):Promise<Report[]>{const db=this.ready();let q:any;if(role==='SUPER_ADMIN')q=query(collection(db,'reports'),limit(500));else if(role==='POLICE_USER'&&thana)q=query(collection(db,'reports'),where('assignedThanaId','==',thana),limit(500));else q=query(collection(db,'reports'),where('reporterId','==',uid),limit(500));const s=await getDocs(q);return s.docs.map(d=>d.data()as Report).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
 async getReportById(id:string,role:UserRole,uid:string,thana?:string):Promise<Report|null>{const db=this.ready();let s=await getDoc(doc(db,'reports',id));if(!s.exists()){const q=query(collection(db,'reports'),where('reportId','==',id),limit(1));const a=await getDocs(q);if(a.empty)return null;s=a.docs[0]}const r=s.data()as Report;if(role==='SUPER_ADMIN'||(role==='PUBLIC_USER'&&r.reporterId===uid)||(role==='POLICE_USER'&&r.assignedThanaId===thana))return r;throw new Error('Unauthorized access to report')}
 async findReportByTracking(id:string,pin:string):Promise<Report|null>{const reportId=id.trim().toUpperCase(),trackingPin=pin.trim();if(!reportId||!trackingPin)return null;const res=await fetch(`/api/public/track?reportId=${encodeURIComponent(reportId)}&pin=${encodeURIComponent(trackingPin)}`);if(res.status===404)return null;if(!res.ok){const body=await res.json().catch(()=>({}));throw new Error(body.error||'Failed to track report');}const body=await res.json();return body.report as Report}
 async createReport(data:Omit<Report,'id'|'reportId'|'status'|'statusHistory'|'createdAt'|'updatedAt'>,person?:Omit<ReportedPerson,'id'|'personId'|'reportId'|'createdAt'>):Promise<Report>{const db=this.ready();const ref=doc(collection(db,'reports'));const now=new Date().toISOString();const rid=`REP-${new Date().getFullYear()}-${Math.floor(100000+Math.random()*900000)}`;const report:Report={...data,id:ref.id,reportId:rid,trackingPin:String(Math.floor(1000+Math.random()*9000)),status:'SUBMITTED',statusHistory:[{status:'SUBMITTED',timestamp:now,updatedBy:data.reporterName||'Citizen Reporter',role:'PUBLIC_USER',notes:'অনলাইনে গোপনীয়ভাবে প্রাথমিক রিপোর্ট জমা হয়েছে।'}],evidenceIds:data.evidenceIds||[],createdAt:now,updatedAt:now};if(person&&(person.name||person.alias||person.description)){const p=doc(collection(db,'reportedPersons'));await setDoc(p,{...person,id:p.id,personId:p.id,reportId:ref.id,createdAt:now});report.reportedPersonId=p.id;report.hasReportedPerson=true}await setDoc(ref,report);await this.logAudit({userId:data.reporterId,userName:data.reporterName,role:'PUBLIC_USER',action:'REPORT_CREATED',reportId:ref.id,metadata:{assignedThanaId:data.assignedThanaId}});await this.createNotification({targetThanaId:data.assignedThanaId,title:'নতুন রিপোর্ট জমা হয়েছে',message:`${data.jurisdiction.thanaName} এ নতুন রিপোর্ট (${rid}) জমা হয়েছে।`,reportId:ref.id});return report}
 async updateReportStatus(id:string,status:ReportStatus,officer:{uid:string;name:string;thanaId:string;role:UserRole},notes?:string,actionDetails?:string):Promise<Report>{const db=this.ready();const ref=doc(db,'reports',id);const s=await getDoc(ref);if(!s.exists())throw new Error('Report not found');const r=s.data()as Report;if(officer.role==='POLICE_USER'&&r.assignedThanaId!==officer.thanaId)throw new Error('Unauthorized');const now=new Date().toISOString();const h={status,timestamp:now,updatedBy:officer.name,role:officer.role,notes:notes||`অবস্থা পরিবর্তিত হয়ে '${status}' করা হয়েছে।`};const next={...r,status,statusHistory:[...(r.statusHistory||[]),h],updatedAt:now,...(notes?{policeNotes:notes}:{}),...(actionDetails?{actionTakenDetails:actionDetails}:{})};await updateDoc(ref,next);await this.logAudit({userId:officer.uid,userName:officer.name,role:officer.role,action:'STATUS_UPDATED',reportId:id,metadata:{newStatus:status,thanaId:r.assignedThanaId}});await this.createNotification({recipientId:r.reporterId,title:'রিপোর্টের অবস্থা হালনাগাদ',message:`আপনার রিপোর্ট (${r.reportId}) এর অবস্থা: ${status}`,reportId:id});return next}
 async getReportedPerson(id:string,role:UserRole,thana?:string):Promise<ReportedPerson|null>{if(role==='PUBLIC_USER')throw new Error('Unauthorized');const db=this.ready();const s=await getDoc(doc(db,'reportedPersons',id));if(!s.exists())return null;const p=s.data()as ReportedPerson;if(role==='POLICE_USER'){const r=await getDoc(doc(db,'reports',p.reportId));if(!r.exists()||(r.data()as Report).assignedThanaId!==thana)throw new Error('Unauthorized')}return p}
 async getEvidenceForReport(reportId:string,role:UserRole,uid:string,thana?:string):Promise<Evidence[]>{const r=await this.getReportById(reportId,role,uid,thana);if(!r)return[];const db=this.ready();const ids=r.evidenceIds||[];if(!ids.length)return[];const snaps=await Promise.all(ids.map(id=>getDoc(doc(db,'evidence',id))));return snaps.filter(s=>s.exists()).map(s=>s.data()as Evidence)}
 async addEvidence(e:Omit<Evidence,'id'|'evidenceId'|'uploadedAt'>):Promise<Evidence>{const db=this.ready();const ref=doc(collection(db,'evidence'));const v:Evidence={...e,id:ref.id,evidenceId:ref.id,uploadedAt:new Date().toISOString()};await setDoc(ref,v);const rr=doc(db,'reports',e.reportId);const s=await getDoc(rr);if(s.exists()){const r=s.data()as Report;await updateDoc(rr,{evidenceIds:Array.from(new Set([...(r.evidenceIds||[]),ref.id])),updatedAt:new Date().toISOString()})}return v}
 async logAudit(l:{userId:string;userName?:string;role:string;action:string;reportId?:string;evidenceId?:string;metadata?:Record<string,any>}):Promise<AuditLog>{const db=this.ready();const ref=doc(collection(db,'auditLogs'));const v:AuditLog={id:ref.id,logId:ref.id,...l,userName:l.userName||'System',timestamp:new Date().toISOString()};await setDoc(ref,v);return v}
 async getAuditLogs():Promise<AuditLog[]>{const s=await getDocs(query(collection(this.ready(),'auditLogs'),orderBy('timestamp','desc'),limit(500)));return s.docs.map(d=>d.data()as AuditLog)}
 async createNotification(n:{targetThanaId?:string;recipientId?:string;title:string;message:string;reportId?:string}):Promise<NotificationItem>{const ref=doc(collection(this.ready(),'notifications'));const v:NotificationItem={id:ref.id,notificationId:`NOTIF-${Date.now()}`,...n,isRead:false,createdAt:new Date().toISOString()};await setDoc(ref,v);return v}
 async getNotifications(thana?:string,uid?:string):Promise<NotificationItem[]>{const db=this.ready();const out=new Map<string,NotificationItem>();if(thana){for(const d of(await getDocs(query(collection(db,'notifications'),where('targetThanaId','==',thana),limit(200)))).docs)out.set(d.id,d.data()as NotificationItem)}if(uid){for(const d of(await getDocs(query(collection(db,'notifications'),where('recipientId','==',uid),limit(200)))).docs)out.set(d.id,d.data()as NotificationItem)}return [...out.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
 async markNotificationAsRead(id:string){await updateDoc(doc(this.ready(),'notifications',id),{isRead:true})}
 async getPoliceUsers():Promise<PoliceUser[]>{const s=await getDocs(query(collection(this.ready(),'policeUsers'),limit(500)));return s.docs.map(d=>d.data()as PoliceUser)}
 async createPoliceUser(o:Omit<PoliceUser,'uid'|'createdAt'> & {password:string}):Promise<PoliceUser>{if(!auth?.currentUser)throw new Error('You must be signed in as Super Admin.');const token=await auth.currentUser.getIdToken(true);const res=await fetch('/api/admin/police-users',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(o)});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Failed to create police account');return data.policeUser as PoliceUser}
 async togglePoliceAccountStatus(uid:string):Promise<PoliceUser|null>{const db=this.ready();const ref=doc(db,'policeUsers',uid);const s=await getDoc(ref);if(!s.exists())return null;const p=s.data()as PoliceUser;const n=!p.isActive;await updateDoc(ref,{isActive:n});return{...p,isActive:n}}
 async getPublicStatistics():Promise<PublicStatistics>{const s=await getDoc(doc(this.ready(),'publicStatistics','summary'));if(s.exists())return s.data()as PublicStatistics;return{totalReports:0,underReview:0,verifiedIncidents:0,actionTaken:0,areasCovered:0,categoryDistribution:[],monthlyTrends:[]}}
}
export const dataService=new DataService();export default dataService;