import {
  District,
  Upazila,
  Thana,
  UnionItem,
  PoliceUser,
  Report,
  ReportedPerson,
  Evidence,
  AuditLog,
  NotificationItem,
  PublicStatistics
} from '../types';

export const INITIAL_DISTRICTS: District[] = [
  { id: 'dist_dhaka', nameEn: 'Dhaka', nameBn: 'ঢাকা', division: 'Dhaka' },
  { id: 'dist_chattogram', nameEn: 'Chattogram', nameBn: 'চট্টগ্রাম', division: 'Chattogram' },
  { id: 'dist_coxsbazar', nameEn: "Cox's Bazar", nameBn: "কক্সবাজার", division: 'Chattogram' },
  { id: 'dist_sylhet', nameEn: 'Sylhet', nameBn: 'সিলেট', division: 'Sylhet' },
  { id: 'dist_rajshahi', nameEn: 'Rajshahi', nameBn: 'রাজশাহী', division: 'Rajshahi' },
  { id: 'dist_khulna', nameEn: 'Khulna', nameBn: 'খুলনা', division: 'Khulna' },
  { id: 'dist_cumilla', nameEn: 'Cumilla', nameBn: 'কুমিল্লা', division: 'Chattogram' },
];

export const INITIAL_UPAZILAS: Upazila[] = [
  { id: 'upz_gulshan', districtId: 'dist_dhaka', nameEn: 'Gulshan', nameBn: 'গুলশান' },
  { id: 'upz_dhanmondi', districtId: 'dist_dhaka', nameEn: 'Dhanmondi', nameBn: 'ধানমন্ডি' },
  { id: 'upz_mirpur', districtId: 'dist_dhaka', nameEn: 'Mirpur', nameBn: 'মিরপুর' },
  { id: 'upz_kotwali_ctg', districtId: 'dist_chattogram', nameEn: 'Kotwali', nameBn: 'কোতোয়ালী' },
  { id: 'upz_teknaf', districtId: 'dist_coxsbazar', nameEn: 'Teknaf', nameBn: 'টেকনাফ' },
  { id: 'upz_sylhet_sadar', districtId: 'dist_sylhet', nameEn: 'Sylhet Sadar', nameBn: 'সিলেট সদর' },
];

export const INITIAL_THANAS: Thana[] = [
  { id: 'thana_gulshan', upazilaId: 'upz_gulshan', districtId: 'dist_dhaka', nameEn: 'Gulshan Thana', nameBn: 'গুলশান থানা', code: 'GLS-01' },
  { id: 'thana_dhanmondi', upazilaId: 'upz_dhanmondi', districtId: 'dist_dhaka', nameEn: 'Dhanmondi Thana', nameBn: 'ধানমন্ডি থানা', code: 'DHN-02' },
  { id: 'thana_mirpur', upazilaId: 'upz_mirpur', districtId: 'dist_dhaka', nameEn: 'Mirpur Model Thana', nameBn: 'মিরপুর মডেল থানা', code: 'MIR-03' },
  { id: 'thana_kotwali_ctg', upazilaId: 'upz_kotwali_ctg', districtId: 'dist_chattogram', nameEn: 'Kotwali Thana (CTG)', nameBn: 'কোতোয়ালী থানা (চট্টগ্রাম)', code: 'CTG-01' },
  { id: 'thana_teknaf', upazilaId: 'upz_teknaf', districtId: 'dist_coxsbazar', nameEn: 'Teknaf Model Thana', nameBn: 'টেকনাফ মডেল থানা', code: 'TKF-01' },
  { id: 'thana_sylhet_sadar', upazilaId: 'upz_sylhet_sadar', districtId: 'dist_sylhet', nameEn: 'Sylhet Kotwali Thana', nameBn: 'সিলেট কোতোয়ালী থানা', code: 'SYL-01' },
];

export const INITIAL_UNIONS: UnionItem[] = [
  { id: 'un_g19', upazilaId: 'upz_gulshan', nameEn: 'Ward 19 (Gulshan 1)', nameBn: 'ওয়ার্ড ১৯ (গুলশান ১)' },
  { id: 'un_g20', upazilaId: 'upz_gulshan', nameEn: 'Ward 20 (Gulshan 2)', nameBn: 'ওয়ার্ড ২০ (গুলশান ২)' },
  { id: 'un_d15', upazilaId: 'upz_dhanmondi', nameEn: 'Ward 15 (Dhanmondi)', nameBn: 'ওয়ার্ড ১৫ (ধানমন্ডি)' },
  { id: 'un_m10', upazilaId: 'upz_mirpur', nameEn: 'Ward 10 (Mirpur 10)', nameBn: 'ওয়ার্ড ১০ (মিরপুর ১০)' },
  { id: 'un_k31', upazilaId: 'upz_kotwali_ctg', nameEn: 'Ward 31 (Kotwali CTG)', nameBn: 'ওয়ার্ড ৩১ (কোতোয়ালী)' },
  { id: 'un_tk1', upazilaId: 'upz_teknaf', nameEn: 'Teknaf Sadar Union', nameBn: 'টেকনাফ সদর ইউনিয়ন' },
];

export const DEMO_POLICE_USERS: PoliceUser[] = [
  {
    uid: 'police_gulshan_01',
    fullName: 'এসআই রফিকুল ইসলাম (SI Rafiqul Islam)',
    email: 'police.gulshan@police.gov.bd',
    badgeNumber: 'BP-8472910',
    rank: 'Sub-Inspector (SI)',
    assignedDistrictId: 'dist_dhaka',
    assignedThanaId: 'thana_gulshan',
    thanaNameBn: 'গুলশান থানা',
    thanaNameEn: 'Gulshan Thana',
    isActive: true,
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    uid: 'police_kotwali_01',
    fullName: 'ইন্সপেক্টর মাহবুব আলম (Inspector Mahbub Alam)',
    email: 'police.kotwali@police.gov.bd',
    badgeNumber: 'BP-7329104',
    rank: 'Inspector (Investigation)',
    assignedDistrictId: 'dist_chattogram',
    assignedThanaId: 'thana_kotwali_ctg',
    thanaNameBn: 'কোতোয়ালী থানা (চট্টগ্রাম)',
    thanaNameEn: 'Kotwali Thana (CTG)',
    isActive: true,
    createdAt: '2026-01-12T11:00:00Z',
  },
  {
    uid: 'police_teknaf_01',
    fullName: 'ওসি সাইফুল করিম (OC Saiful Karim)',
    email: 'police.teknaf@police.gov.bd',
    badgeNumber: 'BP-6102834',
    rank: 'Officer-in-Charge (OC)',
    assignedDistrictId: 'dist_coxsbazar',
    assignedThanaId: 'thana_teknaf',
    thanaNameBn: 'টেকনাফ মডেল থানা',
    thanaNameEn: 'Teknaf Model Thana',
    isActive: true,
    createdAt: '2026-01-15T09:30:00Z',
  }
];

export const DEMO_REPORTS: Report[] = [
  {
    id: 'rep_101',
    reportId: 'REP-2026-DH-101',
    reporterId: 'citizen_demo_01',
    reporterName: 'তানভীর আহমেদ',
    reporterPhone: '01711-234567',
    trackingPin: '4821',
    jurisdiction: {
      districtId: 'dist_dhaka',
      districtName: 'ঢাকা',
      upazilaId: 'upz_gulshan',
      upazilaName: 'গুলশান',
      thanaId: 'thana_gulshan',
      thanaName: 'গুলশান থানা',
      unionId: 'un_g19',
      unionName: 'ওয়ার্ড ১৯ (গুলশান ১)',
      villageArea: 'গুলশান ১ ডিএনসিসি মার্কেটের পেছনের গলি',
      roadLandmark: 'রোড ১৩, ব্লক সি এর নিকটবর্তী খোলা মাঠ',
    },
    incidentType: 'YABA',
    description: 'সন্ধ্যা ৭টার পর গলির মুখে সন্দেহজনক মোটরসাইকেল আরোহীদের উপস্থিতি লক্ষ্য করা যায়। কিছু তরুণের মাঝে সন্দেহজনক ইয়াবা ট্যাবলেট লেনদেন হতে দেখা গেছে।',
    incidentDate: '2026-10-06',
    incidentTime: '19:45',
    location: {
      latitude: 23.7788,
      longitude: 90.4193,
      generalArea: 'গুলশান ১ এলাকা',
    },
    hasReportedPerson: true,
    reportedPersonId: 'person_101',
    evidenceIds: ['ev_101'],
    assignedThanaId: 'thana_gulshan',
    status: 'VERIFIED',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-10-06T20:10:00Z',
        updatedBy: 'Citizen Reporter',
        role: 'PUBLIC_USER',
        notes: 'নাগরিক কর্তৃক অনলাইনে প্রাথমিক রিপোর্ট দাখিল করা হয়েছে।',
      },
      {
        status: 'UNDER_REVIEW',
        timestamp: '2026-10-06T21:00:00Z',
        updatedBy: 'SI Rafiqul Islam (Gulshan Thana)',
        role: 'POLICE_USER',
        notes: 'তদন্তকারী কর্মকর্তা নিয়োগ করা হয়েছে এবং সিসিটিভি ফুটেজ যাচাই প্রক্রিয়াধীন।',
      },
      {
        status: 'VERIFIED',
        timestamp: '2026-10-07T11:30:00Z',
        updatedBy: 'SI Rafiqul Islam (Gulshan Thana)',
        role: 'POLICE_USER',
        notes: 'স্থানীয় গোয়েন্দা নজরদারিতে তথ্যের প্রাথমিক সত্যতা নিশ্চিত করা হয়েছে। অভিযান টিম প্রস্তুত হচ্ছে।',
      }
    ],
    policeNotes: 'সিসিটিভি ফুটেজে উল্লিখিত মোটরসাইকেলের নম্বর প্লেট অস্পষ্ট হলেও সন্দেহভাজন ব্যক্তির চলাচল নজরদারিতে রাখা হয়েছে।',
    actionTakenDetails: '',
    createdAt: '2026-10-06T20:10:00Z',
    updatedAt: '2026-10-07T11:30:00Z',
  },
  {
    id: 'rep_102',
    reportId: 'REP-2026-DH-102',
    reporterId: 'citizen_demo_02',
    reporterName: 'গোপনীয় নাগরিক',
    reporterPhone: '01812-998877',
    trackingPin: '5912',
    jurisdiction: {
      districtId: 'dist_dhaka',
      districtName: 'ঢাকা',
      upazilaId: 'upz_gulshan',
      upazilaName: 'গুলশান',
      thanaId: 'thana_gulshan',
      thanaName: 'গুলশান থানা',
      unionId: 'un_g20',
      unionName: 'ওয়ার্ড ২০ (গুলশান ২)',
      villageArea: 'গুলশান ২ লেকপাড় সংলগ্ন ওয়াকওয়ে',
      roadLandmark: 'ব্রিজের পশ্চিম পাশ',
    },
    incidentType: 'GANJA',
    description: 'রাতের বেলা নির্জন লেকপাড়ে কয়েকজন মাদক সেবন করে এবং পথচারীদের উত্ত্যক্ত করার আশঙ্কা রয়েছে।',
    incidentDate: '2026-10-07',
    incidentTime: '22:15',
    location: {
      latitude: 23.7925,
      longitude: 90.4150,
      generalArea: 'গুলশান ২ লেকপাড়',
    },
    hasReportedPerson: false,
    evidenceIds: [],
    assignedThanaId: 'thana_gulshan',
    status: 'UNDER_REVIEW',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-10-07T22:40:00Z',
        updatedBy: 'Citizen Reporter',
        role: 'PUBLIC_USER',
        notes: 'রিপোর্ট প্রাপ্তি স্বীকার।',
      },
      {
        status: 'UNDER_REVIEW',
        timestamp: '2026-10-08T08:00:00Z',
        updatedBy: 'SI Rafiqul Islam (Gulshan Thana)',
        role: 'POLICE_USER',
        notes: 'প্যাট্রোল টিমের রুট প্ল্যানে লেকপাড় অন্তর্ভুক্ত করা হয়েছে।',
      }
    ],
    policeNotes: 'রাতের প্যাট্রোল পেট্রোলিং দল পাঠানো হবে।',
    actionTakenDetails: '',
    createdAt: '2026-10-07T22:40:00Z',
    updatedAt: '2026-10-08T08:00:00Z',
  },
  {
    id: 'rep_103',
    reportId: 'REP-2026-CTG-103',
    reporterId: 'citizen_demo_03',
    reporterName: 'রহিম উল্লাহ',
    reporterPhone: '01911-345678',
    trackingPin: '9301',
    jurisdiction: {
      districtId: 'dist_chattogram',
      districtName: 'চট্টগ্রাম',
      upazilaId: 'upz_kotwali_ctg',
      upazilaName: 'কোতোয়ালী',
      thanaId: 'thana_kotwali_ctg',
      thanaName: 'কোতোয়ালী থানা (চট্টগ্রাম)',
      unionId: 'un_k31',
      unionName: 'ওয়ার্ড ৩১ (কোতোয়ালী)',
      villageArea: 'আন্দরকিল্লা মোড়ের নিকটবর্তী গোডাউন এলাকা',
      roadLandmark: 'পুরাতন ডাকঘরের পেছনের গলি',
    },
    incidentType: 'PHENSEDYL',
    description: 'পার্সেল আকারে অননুমোদিত কাশির সিরাপ ও নিষিদ্ধ ফেনসিডিল বোতল খালাস করার সন্দেহজনক গতিবিধি লক্ষ্য করা গেছে।',
    incidentDate: '2026-10-05',
    incidentTime: '23:30',
    location: {
      latitude: 22.3384,
      longitude: 91.8385,
      generalArea: 'আন্দরকিল্লা, চট্টগ্রাম',
    },
    hasReportedPerson: true,
    reportedPersonId: 'person_103',
    evidenceIds: ['ev_103'],
    assignedThanaId: 'thana_kotwali_ctg',
    status: 'ACTION_TAKEN',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-10-05T23:55:00Z',
        updatedBy: 'Citizen Reporter',
        role: 'PUBLIC_USER',
        notes: 'রিপোর্ট সাবমিট করা হয়েছে।',
      },
      {
        status: 'UNDER_REVIEW',
        timestamp: '2026-10-06T09:00:00Z',
        updatedBy: 'Inspector Mahbub Alam',
        role: 'POLICE_USER',
        notes: 'গোডাউন মালিকের তথ্যাদি যাচাই ও গোয়েন্দা নজরদারি শুরু।',
      },
      {
        status: 'VERIFIED',
        timestamp: '2026-10-06T15:00:00Z',
        updatedBy: 'Inspector Mahbub Alam',
        role: 'POLICE_USER',
        notes: 'নিষিদ্ধ পদার্থের উপস্থিতি নিশ্চিত।',
      },
      {
        status: 'ACTION_TAKEN',
        timestamp: '2026-10-07T14:00:00Z',
        updatedBy: 'Inspector Mahbub Alam',
        role: 'POLICE_USER',
        notes: 'কোতোয়ালী থানা পুলিশের বিশেষ অভিযানে ৫০ বোতল নিষিদ্ধ সিরাপ জব্দ ও আইনানুগ মামলা রুজু করা হয়েছে।',
      }
    ],
    policeNotes: 'ডিবি টিম সহ যৌথ অভিযান পরিচালিত। জব্দ তালিকা প্রস্তুত করা হয়েছে।',
    actionTakenDetails: 'কোতোয়ালী থানা এফআইআর নং ৪২/২০২৬, ধারা ৩৬(১) সারণির ১৪(গ), মাদকদ্রব্য নিয়ন্ত্রণ আইন ২০১৮।',
    createdAt: '2026-10-05T23:55:00Z',
    updatedAt: '2026-10-07T14:00:00Z',
  },
  {
    id: 'rep_104',
    reportId: 'REP-2026-TKF-104',
    reporterId: 'citizen_demo_01',
    reporterName: 'তানভীর আহমেদ',
    reporterPhone: '01711-234567',
    trackingPin: '7721',
    jurisdiction: {
      districtId: 'dist_coxsbazar',
      districtName: "কক্সবাজার",
      upazilaId: 'upz_teknaf',
      upazilaName: 'টেকনাফ',
      thanaId: 'thana_teknaf',
      thanaName: 'টেকনাফ মডেল থানা',
      unionId: 'un_tk1',
      unionName: 'টেকনাফ সদর ইউনিয়ন',
      villageArea: 'নাফ নদী সংলগ্ন লবণ মাঠ সংলগ্ন এলাকা',
      roadLandmark: 'সীমান্ত বেড়িবাঁধ ৩ নং পোস্টের সন্নিকটে',
    },
    incidentType: 'SUSPECTED_DISTRIBUTION',
    description: 'নৌকাযোগে সন্দেহজনক প্যাকেট স্থানান্তর হতে দেখা গেছে মধ্যরাতে।',
    incidentDate: '2026-10-07',
    incidentTime: '01:20',
    location: {
      latitude: 20.8656,
      longitude: 92.2980,
      generalArea: 'টেকনাফ নাফ নদী সংলগ্ন এলাকা',
    },
    hasReportedPerson: false,
    evidenceIds: [],
    assignedThanaId: 'thana_teknaf',
    status: 'SUBMITTED',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-10-07T08:10:00Z',
        updatedBy: 'Citizen Reporter',
        role: 'PUBLIC_USER',
        notes: 'নাগরিক কর্তৃক সরাসরি অনলাইনে রিপোর্ট প্রেরণ করা হয়েছে।',
      }
    ],
    policeNotes: '',
    actionTakenDetails: '',
    createdAt: '2026-10-07T08:10:00Z',
    updatedAt: '2026-10-07T08:10:00Z',
  }
];

export const DEMO_REPORTED_PERSONS: ReportedPerson[] = [
  {
    id: 'person_101',
    personId: 'person_101',
    reportId: 'rep_101',
    name: 'মো. কামাল হোসেন (সন্দেহভাজন)',
    alias: 'কালা কামাল',
    approximateAge: 32,
    gender: 'পুরুষ',
    description: 'উচ্চতা প্রায় ৫ ফুট ৭ ইঞ্চি, মুখে হালকা দাড়ি, গায়ে কালো জ্যাকেট ও লাল হেলমেট।',
    knownArea: 'গুলশান ১ ডিএনসিসি মার্কেট ও নিকেতন এলাকা',
    additionalNotes: 'সকালে কাঁচাবাজারে থাকে, সন্ধ্যার পর মোটরসাইকেলে ঘুরাঘুরি করে।',
    createdAt: '2026-10-06T20:10:00Z',
  },
  {
    id: 'person_103',
    personId: 'person_103',
    reportId: 'rep_103',
    name: 'সন্দেহভাজন গোডাউন তত্ত্বাবধায়ক',
    alias: 'বাবুল ভাই',
    approximateAge: 45,
    gender: 'পুরুষ',
    description: 'মাঝারি গড়ন, সাদা পাঞ্জাবি ও কালো টুপি পরিহিত থাকে।',
    knownArea: 'আন্দরকিল্লা বক্সিরহাট এলাকা',
    additionalNotes: 'রাতে মাল খালাসের সময় উপস্থিত থাকে।',
    createdAt: '2026-10-05T23:55:00Z',
  }
];

export const DEMO_EVIDENCE: Evidence[] = [
  {
    id: 'ev_101',
    evidenceId: 'ev_101',
    reportId: 'rep_101',
    provider: 'telegram',
    telegramMessageId: 8492,
    telegramFileId: 'AgACAgUAAxkBAAICkm...demo_file_id',
    fileType: 'image/jpeg',
    fileName: 'motorcycle_tea_stall_night.jpg',
    fileSize: 2451200,
    uploadedBy: 'citizen_demo_01',
    uploadedAt: '2026-10-06T20:10:00Z',
    previewUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'ev_103',
    evidenceId: 'ev_103',
    reportId: 'rep_103',
    provider: 'telegram',
    telegramMessageId: 8495,
    telegramFileId: 'BAACAgUAAxkBAAICk2...demo_doc_id',
    fileType: 'image/jpeg',
    fileName: 'carton_boxes_storage.jpg',
    fileSize: 3105400,
    uploadedBy: 'citizen_demo_03',
    uploadedAt: '2026-10-05T23:55:00Z',
    previewUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
  }
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_01',
    logId: 'AUD-001',
    userId: 'police_gulshan_01',
    userName: 'SI Rafiqul Islam (Gulshan Thana)',
    role: 'POLICE_USER',
    action: 'STATUS_UPDATED',
    reportId: 'rep_101',
    ipAddress: '103.114.98.22',
    timestamp: '2026-10-07T11:30:00Z',
    metadata: { previousStatus: 'UNDER_REVIEW', newStatus: 'VERIFIED', thanaId: 'thana_gulshan' },
  },
  {
    id: 'log_02',
    logId: 'AUD-002',
    userId: 'police_gulshan_01',
    userName: 'SI Rafiqul Islam (Gulshan Thana)',
    role: 'POLICE_USER',
    action: 'EVIDENCE_ACCESSED',
    reportId: 'rep_101',
    evidenceId: 'ev_101',
    ipAddress: '103.114.98.22',
    timestamp: '2026-10-07T11:20:00Z',
    metadata: { fileName: 'motorcycle_tea_stall_night.jpg', telegramMessageId: 8492 },
  },
  {
    id: 'log_03',
    logId: 'AUD-003',
    userId: 'citizen_demo_01',
    userName: 'তানভীর আহমেদ',
    role: 'PUBLIC_USER',
    action: 'REPORT_CREATED',
    reportId: 'rep_101',
    ipAddress: '103.205.71.18',
    timestamp: '2026-10-06T20:10:00Z',
    metadata: { assignedThanaId: 'thana_gulshan', incidentType: 'YABA' },
  },
  {
    id: 'log_04',
    logId: 'AUD-004',
    userId: 'admin_central_01',
    userName: 'Md. Shamsul Haque (Central Admin)',
    role: 'SUPER_ADMIN',
    action: 'POLICE_ACCOUNT_CREATED',
    ipAddress: '103.48.16.5',
    timestamp: '2026-10-01T09:00:00Z',
    metadata: { createdOfficer: 'SI Rafiqul Islam', assignedThana: 'thana_gulshan' },
  }
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_01',
    notificationId: 'NOTIF-101',
    targetThanaId: 'thana_gulshan',
    title: 'নতুন রিপোর্ট জমা হয়েছে',
    message: 'গুলশান থানা এলাকায় একটি নতুন সন্দেহজনক মাদক ঘটনার রিপোর্ট জমা হয়েছে (REP-2026-DH-102)।',
    reportId: 'rep_102',
    isRead: false,
    createdAt: '2026-10-07T22:40:00Z',
  },
  {
    id: 'notif_02',
    notificationId: 'NOTIF-102',
    targetThanaId: 'thana_gulshan',
    title: 'তদন্ত যাচাই প্রয়োজনীয়',
    message: 'রিপোর্ট REP-2026-DH-101 এ নতুন গোপনীয় প্রমাণ পর্যালোচনা করুন।',
    reportId: 'rep_101',
    isRead: true,
    createdAt: '2026-10-06T20:15:00Z',
  },
  {
    id: 'notif_03',
    notificationId: 'NOTIF-103',
    targetThanaId: 'thana_kotwali_ctg',
    title: 'আইনগত ব্যবস্থা আপডেট',
    message: 'কোতোয়ালী থানায় আন্দরকিল্লা মাদক রিপোর্টটিতে ব্যবস্থা গৃহীত হিসেবে নথিভুক্ত হয়েছে।',
    reportId: 'rep_103',
    isRead: false,
    createdAt: '2026-10-07T14:05:00Z',
  }
];

export const DEMO_PUBLIC_STATS: PublicStatistics = {
  totalReports: 1428,
  underReview: 184,
  verifiedIncidents: 812,
  actionTaken: 365,
  areasCovered: 64,
  categoryDistribution: [
    { category: 'YABA', nameBn: 'ইয়াবা / মেথাম্ফেটামিন', nameEn: 'Yaba / Meth', count: 520 },
    { category: 'GANJA', nameBn: 'গাঁজা / ক্যানাবিস', nameEn: 'Ganja / Cannabis', count: 340 },
    { category: 'PHENSEDYL', nameBn: 'ফেনসিডিল / সিরাপ', nameEn: 'Phensedyl', count: 215 },
    { category: 'HEROIN', nameBn: 'হেরোইন', nameEn: 'Heroin', count: 148 },
    { category: 'TRAMADOL_TABLETS', nameBn: 'ব্যথানাশক ও অন্যান্য ট্যাবলেট', nameEn: 'Tramadol Tablets', count: 125 },
    { category: 'OTHER', nameBn: 'অন্যান্য সন্দেহজনক মাদক', nameEn: 'Other Narcotics', count: 80 },
  ],
  monthlyTrends: [
    { month: 'মে', count: 182 },
    { month: 'জুন', count: 210 },
    { month: 'জুলাই', count: 245 },
    { month: 'আগস্ট', count: 298 },
    { month: 'সেপ্টেম্বর', count: 325 },
    { month: 'অক্টোবর', count: 168 },
  ]
};
