import React,{createContext,useContext,useEffect,useState}from'react';import{User,PoliceUser,UserRole}from'../types';import{auth,db,isFirebaseConfigured}from'../lib/firebase';import{onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut as fbSignOut}from'firebase/auth';import{doc,getDoc,setDoc}from'firebase/firestore';
export interface AuthContextType{currentUser:User|null;policeUser:PoliceUser|null;role:UserRole;isAuthenticated:boolean;isLoading:boolean;loginAsPublic:(e:string,p:string)=>Promise<void>;loginAsPolice:(e:string,p:string)=>Promise<boolean>;loginAsAdmin:(e:string,p:string)=>Promise<void>;registerPublic:(n:string,e:string,ph:string|undefined,p:string)=>Promise<void>;logout:()=>Promise<void>;switchDemoRole:(r:UserRole,t?:string)=>void}
const C=createContext<AuthContextType|undefined>(undefined);
export const AuthProvider:React.FC<{children:React.ReactNode}>=({children})=>{const[currentUser,setCurrentUser]=useState<User|null>(null),[policeUser,setPoliceUser]=useState<PoliceUser|null>(null),[role,setRole]=useState<UserRole>('PUBLIC_USER'),[isLoading,setIsLoading]=useState(true);
useEffect(()=>{if(!isFirebaseConfigured||!auth||!db){setIsLoading(false);return}return onAuthStateChanged(auth,async fb=>{try{if(!fb){setCurrentUser(null);setPoliceUser(null);setRole('PUBLIC_USER');return}const s=await getDoc(doc(db!,'users',fb.uid));if(!s.exists()){await fbSignOut(auth!);return}const u=s.data()as User;if(u.role==='POLICE_USER'){const p=await getDoc(doc(db!,'policeUsers',fb.uid));if(!p.exists()||(p.data()as PoliceUser).isActive===false){await fbSignOut(auth!);return}setPoliceUser(p.data()as PoliceUser)}else setPoliceUser(null);setCurrentUser(u);setRole(u.role)}catch(e){console.error(e);setCurrentUser(null);setPoliceUser(null)}})} ,[]);
const need=()=>{if(!isFirebaseConfigured||!auth||!db)throw new Error('Firebase is not configured. Configure VITE_FIREBASE_* environment variables.')};
const login=async(e:string,p:string,expected:UserRole)=>{need();const c=await signInWithEmailAndPassword(auth!,e.trim(),p);const s=await getDoc(doc(db!,'users',c.user.uid));if(!s.exists())throw new Error('User profile is missing.');const u=s.data()as User;if(u.role!==expected){await fbSignOut(auth!);throw new Error('Unauthorized portal role.')}}; 
const loginAsPublic=(e:string,p:string)=>login(e,p,'PUBLIC_USER');const loginAsPolice=async(e:string,p:string)=>{await login(e,p,'POLICE_USER');return true};const loginAsAdmin=(e:string,p:string)=>login(e,p,'SUPER_ADMIN');
const registerPublic=async(n:string,e:string,ph:string|undefined,p:string)=>{need();const c=await createUserWithEmailAndPassword(auth!,e.trim(),p);const u:User={uid:c.user.uid,fullName:n.trim(),email:e.trim(),phoneNumber:ph?.trim(),role:'PUBLIC_USER',createdAt:new Date().toISOString()};await setDoc(doc(db!,'users',c.user.uid),u);setCurrentUser(u);setRole('PUBLIC_USER')};
const logout=async()=>{if(auth)await fbSignOut(auth);setCurrentUser(null);setPoliceUser(null);setRole('PUBLIC_USER')};const switchDemoRole=()=>{throw new Error('Demo role switching is disabled.')};
return <C.Provider value={{currentUser,policeUser,role,isAuthenticated:!!currentUser,isLoading,loginAsPublic,loginAsPolice,loginAsAdmin,registerPublic,logout,switchDemoRole}}>{children}</C.Provider>};export const useAuth=()=>{const c=useContext(C);if(!c)throw new Error('useAuth must be used within AuthProvider');return c};